version: '3.9'
services:
  java_app:
    container_name: java_app
    image: java_app:1.0.0
    build: .
    ports:
      - 8093:8093
    environment:
      - DATABASE_URL=jdbc:mysql://localhost/inventario?useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mauricio2004
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mauricio2004
      MYSQL_DATABASE: dbc:mysql://localhost/inventario?useSSL=false







